### ISSUE TITLE
Help me Implement Custom Agent for Backlog Optimization

### ISSUE THREAD

**Issue by sebastienfi** [kreneskyp/ix#302] opened 2023-10-23 11:08 UTC
📢 **Calling All Problem Solvers!** 📢

Given just 3 days, I reverse-engineered a backlog for an aging monolithic app without any existing one. Using a multi-step manual prompting method, I extracted around 500 user stories. These stories are "isolated" since my method wasn't aware of prior created stories. The goal now is a coherent backlog for a total app rewrite with Domain-Driven Design and microservices. And yes, my deadline is 26th October to provide the backlog :) 

**The Challenge:**

The backlog has redundant stories, misplaced user stories, and other non-optimal structures. The mission? Process it and create a streamlined version.

- Clarity: Each User Story should clearly describe the desired outcome from a user's perspective. The "who", "what", and "why" should be evident.
- Value: The User Stories should clearly deliver value to the end user or the business.
- Independence: Ideally, User Stories should be independent of each other so they can be developed, tested, and released in any sequence.
- Epic Granularity: An Epic should represent a larger chunk of work that encompasses multiple related User Stories. It should be thematic and provide a clear narrative of the work.
- Feasibility: Check if there are any technical challenges or dependencies in the User Stories that need to be addressed.
- Consistency: Ensure there are no overlapping or contradictory User Stories.
- Related Components: This column should help in identifying technical components or modules that would be affected. Ensure they are correctly identified.
- Epic ID: Ensure that the User Stories are correctly mapped to their respective Epics.

**Key Steps:**

1. **CSV Processing:** Load a CSV with ~500 entries consisting of Epics and User Stories. The CSV format is `ID, Description, Tags, ParentId`. Tags are a comma-separated list categorizing the user-story. Description is a typical one-liner about the task "As..., I need to ..., in order to ...".
2. **Domain Clarification:** Post-loading, the agent should discern the software's domain. The agent should ask the user a series of questions to clarify the domain. 
3. **Epic Refinement:** The agent should propose a systematic approach to restructure epics, ensuring thematic coherence. This step might involve regrouping epics under new or existing thematics.
4. **User Story Refinement:** The agent should consider ways to reassign and potentially merge user stories for maximum clarity and relevance.
5. **Tagging Insight:** The agent should suggest potential tags for each user story based on its content and its epic. User should have the option to approve, modify, or retry these tag suggestions. Once approved, the agent should apply the tags to the user stories.
6. **Output:** The agent's final task is to save this polished backlog as a CSV.

How would you approach this? Can you envision an agent design flow or have questions to shape the direction? Your insights could be the game-changer as I am new to IX and don't have a clear vision of components! 🚀

**Comment by kreneskyp** [comment] 2023-10-27 13:39
Closing this as it is not a bug report or feature request for IX.

**Closed by kreneskyp** 2023-10-27 13:39 UTC
